---
- name: Install nextcloud from snapcraft
  shell: snap install nextcloud
    
- name: Setup nextcloud on the system
  shell: snap run nextcloud.manual-install {{ nextcloudAdminUsername }} {{ nextcloudAdminPassword }}
  
- name: Setup a self-signed SSL cert
  shell: snap run nextcloud.enable-https self-signed
  when: useSSL_selfSigned == true

- name: Setup a lets-encrypt SSL cert
  shell: expect -c "spawn /snap/bin/nextcloud.enable-https lets-encrypt; expect -exact \"Have you met these requirements? (y/n) \"; send \"y\r\"; expect \"Please enter an email address (for urgent notices or key recovery)\"; send \"{{ useSSL_letsEncrypt_recoveryEmail }}\r\"; expect \"Please enter your domain name(s) (space-separated)\"; send \"{{ serverDomain }}\r\"; expect eof"
  when: useSSL_letsEncrypt == true
  
- name: Add hostnames, domains, and IP addresses as trusted domains {1..3}
  shell: snap run nextcloud.occ config:system:set trusted_domains 1 --value="$(hostname)"
  shell: snap run nextcloud.occ config:system:set trusted_domains 2 --value="$(hostname -i)"
  shell: snap run nextcloud.occ config:system:set trusted_domains 3 --value="{{ serverDomain }}"

- name: Restart snap
  shell: snap restart nextcloud